### PR TITLE
fix: start with .

### LINKED ISSUE #9: Relative paths with . are not handled correctly
Depending on if a relative path starts with a "." or not, the same diff will give different results.

```
        let path_a = PathBuf::new(r"a\b\c");
        let path_a_with_dot = PathBuf::new(r".\a\b\c");
        let path_b = PathBuf::new(r"a\e\g");
        let expected_diff_a_to_b = PathBuf::new(r"..\..\..\e\g");

       assert_eq!( pathdiff::diff_paths(&path_b, &path_a).unwrap(), expected_diff_a_to_b ); // Will work fine
       assert_eq!( pathdiff::diff_paths(&path_b, &path_a_with_dot).unwrap(), expected_diff_a_to_b ); // Will panic
```

The second assert will fail with the left hand side being r"a/../../../../e/g/"

### PR DESCRIPTION
**Pull request by cheeslide**
./foo and foo are the same

fix #9

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -57,6 +57,14 @@ where
...
         let mut ita = path.components();
         let mut itb = base.components();
+
+        // ./foo and foo are the same
+        if let Some(Component::CurDir) = ita.clone().next() {
+            ita.next();
+        }
+        if let Some(Component::CurDir) = itb.clone().next() {
+            itb.next();
+        }
```
Comment (whitty) [inline src/lib.rs:68]: Should this be in the loop?  what about `"foo/./bar"` and `"foo/bar"`

Maybe even in a while loop?
*   `"././foo"` and `"foo"`  
*  or `"foo/././bar" and `"foo/bar"`.

Comment (cheeslide) [reply src/lib.rs:68]: @whitty At least [after 1.31.0](https://doc.rust-lang.org/1.31.0/std/path/struct.Path.html#method.components), components() will normalize the path: "Occurrences of `.` are normalized away, except if they are at the beginning of the path."

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
CI fails

**Comment by cheeslide** [comment]
> CI fails

that may because I forget the utf8_paths module. Please try the CI again now.

**Review by Manishearth — APPROVED** [review]
